
lang: en-US
title: Georgetown Board Games
email:
description:



theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"